//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Forms.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Windows.Forms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 .dtree {
        ///	font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;
        ///	font-size: 11px;
        ///	color: #666;
        ///	white-space: nowrap;
        ///}
        ///.dtree img {
        ///	border: 0px;
        ///	vertical-align: middle;
        ///}
        ///.dtree a {
        ///	color: #333;
        ///	text-decoration: none;
        ///}
        ///.dtree a.node, .dtree a.nodeSel {
        ///	white-space: nowrap;
        ///	padding: 1px 2px 1px 2px;
        ///}
        ///.dtree a.node:hover, .dtree a.nodeSel:hover {
        ///	color: #333;
        ///	text-decoration: underline;
        ///}
        ///.dtree a.nodeSel {
        ///	background-color: #c0d2ec;
        ///}
        ///.dtree .clip {
        ///	overflow: hidd [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ___dtree_css {
            get {
                return ResourceManager.GetString("___dtree_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // Node object
        ///function Node(id, pid, name, url, title, target, icon, iconOpen, open) {
        ///	this.id = id;//ID
        ///	this.pid = pid;//parent Node ID
        ///	this.name = name;//Node Text
        ///	this.url = url;//Url Link
        ///	this.title = title;
        ///	this.target = target;
        ///	this.icon = icon;
        ///	this.iconOpen = iconOpen;
        ///	this._io = open || false;
        ///	this._is = false;
        ///	this._ls = false;
        ///	this._hc = false;
        ///	this._ai = 0;
        ///	this._p;
        ///};
        ///
        ///// Tree object
        ///function dTree(objName) {
        ///	this.config = {
        ///		target					: null,
        ///		folderLin [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ___dtree_js {
            get {
                return ResourceManager.GetString("___dtree_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta name=&quot;generator&quot; content=&quot;Generated by Htm Explorer	QQ450640526&quot;&gt;&lt;link rel=&quot;StyleSheet&quot; href=&quot;___dtree.css&quot; type=&quot;text/css&quot; /&gt;
        ///&lt;script type=&quot;text/javascript&quot; src=&quot;___dtree.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;div class=&quot;dtree&quot;&gt;
        ///&lt;p&gt;&lt;a href=&quot;javascript: d.openAll();&quot;&gt;展开&lt;/a&gt; | &lt;a href=&quot;javascript: d.closeAll();&quot;&gt;合并&lt;/a&gt;&lt;/p&gt;
        ///
        ///{0}
        ///
        ///&lt;/div&gt;
        ///&lt;p \&gt;&lt;hr size=&quot;1&quot; \&gt;
        ///&lt;FONT class=dtree&gt;Generated by &lt;A 
        ///href=&quot;http://www.cnblogs.com/xe2011/p/3859801.html&quot; target=&quot;_black&quot;&gt;&lt;FONT color=#0000ff&gt;Htm 
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ___left_htm {
            get {
                return ResourceManager.GetString("___left_htm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _base {
            get {
                object obj = ResourceManager.GetObject("_base", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap empty {
            get {
                object obj = ResourceManager.GetObject("empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap folderopen {
            get {
                object obj = ResourceManager.GetObject("folderopen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap join {
            get {
                object obj = ResourceManager.GetObject("join", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap joinbottom {
            get {
                object obj = ResourceManager.GetObject("joinbottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap line {
            get {
                object obj = ResourceManager.GetObject("line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;HTML&gt;&lt;HEAD&gt;&lt;TITLE&gt;{0}&lt;/TITLE&gt;
        ///&lt;/HEAD&gt;&lt;FRAMESET border=4 cols=&quot;400, *&quot;&gt;
        ///&lt;FRAME name=left marginWidth=5 marginHeight=5 src=&quot;Data\___left.htm&quot; &gt;
        ///&lt;FRAME name=body marginWidth=5 marginHeight=5 src=&quot;&quot; &gt;
        ///&lt;/FRAMESET&gt;
        ///&lt;/HTML&gt; 的本地化字符串。
        /// </summary>
        internal static string MainPage_htm {
            get {
                return ResourceManager.GetString("MainPage_htm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap minus {
            get {
                object obj = ResourceManager.GetObject("minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap minusbottom {
            get {
                object obj = ResourceManager.GetObject("minusbottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap nolines_minus {
            get {
                object obj = ResourceManager.GetObject("nolines_minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap nolines_plus {
            get {
                object obj = ResourceManager.GetObject("nolines_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap page {
            get {
                object obj = ResourceManager.GetObject("page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap plus {
            get {
                object obj = ResourceManager.GetObject("plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap plusbottom {
            get {
                object obj = ResourceManager.GetObject("plusbottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
