//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.33440
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace htmExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("htmExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;HTML&gt;&lt;HEAD&gt;&lt;TITLE&gt;关于&lt;/TITLE&gt;
        ///&lt;META content=&quot;text/html; charset=unicode&quot; http-equiv=Content-Type&gt;
        ///&lt;META name=GENERATOR content=&quot;MSHTML 11.00.9600.16384&quot;&gt;&lt;/HEAD&gt;
        ///&lt;BODY style=&quot;MARGIN: 5px&quot;&gt;
        ///&lt;P&gt;&amp;nbsp;&lt;/P&gt;
        ///&lt;P&gt;【2014年8月7日】&lt;/P&gt;
        ///&lt;OL&gt;
        ///  &lt;LI&gt;美化了主界面&lt;/LI&gt;&lt;/OL&gt;
        ///&lt;P&gt;【2014年8月6日】&lt;/P&gt;
        ///&lt;OL&gt;
        ///  &lt;LI&gt;+ 美化文件列表画线的功能&lt;/LI&gt;&lt;/OL&gt;
        ///&lt;P&gt;&amp;nbsp;&lt;/P&gt;
        ///&lt;P&gt;【2014年8月5日】&lt;/P&gt;
        ///&lt;OL&gt;
        ///  &lt;LI&gt;修复新建立一个文件当先重命名文件时时再粘贴文件名变成HTMLEDIT中的第一行字符&lt;/LI&gt;&lt;/OL&gt;
        ///&lt;P&gt;【2014年7月29日】&lt;/P&gt;
        ///&lt;OL&gt;
        ///  &lt;LI&gt;修 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 关于 {
            get {
                return ResourceManager.GetString("关于", resourceCulture);
            }
        }
    }
}
